.github/workflows/static.yml
composer.json
vendor-bin/php-cs-fixer/composer.json
vendor-bin/phpstan/composer.json
vendor-bin/psalm/composer.json

This makes it easier to add php extensions

Use vendor-bin

---

src/bref/src/LaravelHttpHandler.php
src/bref/src/SymfonyHttpHandler.php

Fixes the content type in the symfony request getting set to the default `application/x-www-form-urlencoded`.

Added missing SERVER variables including the content-type

---

src/bref/src/ConsoleApplicationRunner.php

We need to control this in the runtime.

[Bref][Console] Do not auto exit

---

src/bref/README.md
src/bref/composer.json
src/bref/src/LaravelHttpHandler.php
src/bref/src/SymfonyHttpHandler.php
src/bref/src/SymfonyRequestBridge.php
src/bref/tests/SymfonyRequestBridgeTest.php

Convert to proper Symfony requests

---

composer.json
src/bref/composer.json
src/google-cloud/composer.json
src/laravel/composer.json
src/psr-guzzle/composer.json
src/psr-laminas/composer.json
src/psr-nyholm-laminas/composer.json
src/psr-nyholm/composer.json
src/reactphp/composer.json
src/roadrunner-nyholm/composer.json
src/roadrunner-symfony-nyholm/composer.json
src/swoole/composer.json

This is okey since Symfony 5.3-beta1 is released.

Show that we support runtime 5.3

---

README.md
composer.json
src/psr-17/.github/FUNDING.yml
src/psr-17/.gitignore
src/psr-17/LICENSE
src/psr-17/README.md
src/psr-17/composer.json
src/psr-17/phpunit.xml.dist
src/psr-17/runtime/Message/ResponseInterfaceRuntime.php
src/psr-17/runtime/Message/ServerRequestInterfaceRuntime.php
src/psr-17/runtime/Server/RequestHandlerInterfaceRuntime.php
src/psr-17/src/Emitter.php
src/psr-17/src/EmitterException.php
src/psr-17/src/Runtime.php
src/psr-17/tests/AutoDiscoverTest.php
src/psr-17/tests/phpt/autoload.php
src/psr-17/tests/phpt/psr15.php
src/psr-17/tests/phpt/psr15.phpt
src/psr-17/tests/phpt/psr7.php
src/psr-17/tests/phpt/psr7.phpt

This will require you to install an extra package and add config

Add a generic PSR-17 runtime

---

composer.json
src/bref/CHANGELOG.md
src/bref/composer.json
src/google-cloud/CHANGELOG.md
src/google-cloud/composer.json
src/laravel/CHANGELOG.md
src/laravel/composer.json
src/psr-17/CHANGELOG.md
src/psr-17/composer.json
src/psr-guzzle/CHANGELOG.md
src/psr-guzzle/composer.json
src/psr-laminas/CHANGELOG.md
src/psr-laminas/composer.json
src/psr-nyholm-laminas/CHANGELOG.md
src/psr-nyholm-laminas/composer.json
src/psr-nyholm/CHANGELOG.md
src/psr-nyholm/composer.json
src/reactphp/CHANGELOG.md
src/reactphp/composer.json
src/roadrunner-nyholm/CHANGELOG.md
src/roadrunner-nyholm/composer.json
src/roadrunner-symfony-nyholm/composer.json
src/swoole/CHANGELOG.md
src/swoole/composer.json

Just make sure it is installable

Adding support for Symfony 6

---

src/bref/README.md

From https://bref.sh/docs/web-apps/cron.html

[Bref] Update readme to be more clear about scheduled commands

---

README.md

Added note about sessions

---

src/swoole-nyholm/src/ServerFactory.php

[SwooleNyholm] Add option for swoole socket type

---

psalm.baseline.xml
src/bref/src/BrefRunner.php
src/bref/src/ConsoleApplicationRunner.php

This will be supported in Bref 1.3
See https://github.com/brefphp/bref/pull/1031

[Bref] Add layer name

---

src/bref/composer.json
src/bref/src/BrefRunner.php
src/bref/src/ConsoleApplicationHandler.php
src/bref/src/ConsoleApplicationRunner.php
src/bref/src/Lambda/ContextBuilder.php
src/bref/src/Lambda/LambdaClient.php

This PR aims to avoid using internal classes from `bref/bref`. 
This will make `runtime/bref` more stable.

[Bref] Dont use internal classes from bref/bref

---

src/bref/CHANGELOG.md
src/bref/README.md
src/bref/composer.json

This will explain better how to use Bref. 
We use the `runtime/bref-layer` to simplify installation

[Bref] Update readme

---

src/bref/src/LocalRunner.php

This is nicer when you debug things

[Bref] Echo out response when running bref locally

---

src/roadrunner-symfony-nyholm/README.md

I did not know that I have to provide `env` to the `.rr.yaml` config file and as a newbie, I put it only to the `.env` file. These systems work differently than Symfony I had to spend a lot of time to find this information.

Roadrunner Nyholm - Add information about Roadrunner server env config to README

---

src/google-cloud/phpunit.xml.dist
src/laravel/phpunit.xml.dist
src/roadrunner-nyholm/phpunit.xml.dist
src/roadrunner-symfony-nyholm/phpunit.xml.dist

Currently phpunit fails as the phptd directory does not exists in this projects.

Fix failing phpunit test

---

src/bref/src/LaravelHttpHandler.php
src/bref/src/SymfonyHttpHandler.php
src/bref/src/SymfonyRequestBridge.php
src/bref/tests/SymfonyRequestBridgeTest.php

Fix custom trusted proxies configuration

---

src/bref/src/LocalRunner.php

Just to avoid "Array to string conversion"

[Bref] LocalRunner: Print array result

---

.github/workflows/ci.yml
.github/workflows/static.yml
.php-cs-fixer.php
composer.json
psalm.baseline.xml
src/bref/composer.json
src/google-cloud/composer.json
src/google-cloud/google/CloudEvent.php
src/google-cloud/src/Runtime.php
src/laravel/composer.json
src/psr-17/composer.json
src/psr-17/src/Runtime.php
src/psr-guzzle/composer.json
src/psr-guzzle/src/Runtime.php
src/psr-laminas/composer.json
src/psr-laminas/src/Runtime.php
src/psr-nyholm-laminas/composer.json
src/psr-nyholm-laminas/src/Runtime.php
src/psr-nyholm/composer.json
src/psr-nyholm/src/Runtime.php
src/reactphp/composer.json
src/reactphp/tests/RunnerTest.php
src/roadrunner-nyholm/composer.json
src/roadrunner-symfony-nyholm/composer.json
src/swoole-nyholm/composer.json
src/swoole/composer.json

Drop PHP 7 and fix compatibility with SF6

---

src/bref/src/LocalRunner.php

If we drop PHP7 (#121) we can merge this.

[Bref] Local handler print get_debug_type

---

.github/workflows/ci.yml
.github/workflows/static.yml

Related to: https://github.com/php-runtime/runtime/pull/124
Which requires PHP 8.2

Run CI checks on PHP 8.2

---

src/frankenphp-symfony/README.md

`APP_RUNTIME` have to be available in your container
Thanks for your review !

[Frankenphp Symfony] Define `APP_RUNTIME` environment variable

---

README.md

docs: link to current Symfony documentation page

---

src/roadrunner-symfony-nyholm/composer.json

feat(road-runner): allow ^2023.1.0 and ^2.0

---

src/frankenphp-symfony/src/Runner.php

Tiny refactoring as suggested in https://github.com/php-runtime/runtime/pull/148#discussion_r1375910285

frankenphp-symfony: tiny refactoring

---

src/frankenphp-symfony/src/Runner.php

See https://github.com/dunglas/frankenphp/pull/316 and https://github.com/dunglas/frankenphp/issues/310#issuecomment-1821833524.

frankenphp: don't stop the worker script even if a connection with a client is aborted

---

src/frankenphp-symfony/CHANGELOG.md
src/frankenphp-symfony/README.md
src/frankenphp-symfony/src/Runner.php
src/frankenphp-symfony/src/Runtime.php
src/frankenphp-symfony/tests/RunnerTest.php

See https://github.com/dunglas/frankenphp/issues/280.

frankenphp: add frankenphp_loop_max option

---

.github/workflows/ci.yml
src/swoole-nyholm/CHANGELOG.md
src/swoole-nyholm/composer.json
src/swoole-nyholm/tests/Unit/RequestHandlerRunnerTest.php
src/swoole/CHANGELOG.md
src/swoole/composer.json
src/swoole/src/SymfonyHttpBridge.php
src/swoole/tests/Unit/SymfonyHttpBridgeTest.php

Also dropped PHP 8.0 and make sure we support open-swoole

Prepare for new swoole releases

---

.github/workflows/static.yml
composer.json
psalm.baseline.xml
src/frankenphp-symfony/CHANGELOG.md
src/frankenphp-symfony/composer.json
src/psr-laminas/composer.json
src/psr-nyholm-laminas/composer.json

Prepare release for Franken

---

src/roadrunner-nyholm/CHANGELOG.md

Release 0.1.2 of roadrunner-number
