php-runtime/runtime

src/bref/src/LaravelHttpHandler.php
Otherwise html responses may get incorrectly rendered as text due to the missing content-type header. Indeed, I have seen this issue. ;)
=> Call the prepare method

.gitignore, composer.json, src/roadrunner-symfony-nyholm/src/Runner.php, src/roadrunner-symfony-nyholm/src/Runtime.php
Fix parts of #46
The session still have the following problems::
=> Add session handling to roadrunner symfony bridge

src/swoole/src/LaravelRunner.php, src/swoole/src/SymfonyRunner.php
This PR changes the key case of the `$server` array so matches can be made.
It also manually sets the `HeaderBag` because headers are not sent as `HTTP_*` keys on Swoole's Request `$server`.
=> Fixed server key case and manually setting headers

src/roadrunner-symfony-nyholm/composer.json, src/roadrunner-symfony-nyholm/src/Runner.php, src/roadrunner-symfony-nyholm/src/Runtime.php, src/roadrunner-symfony-nyholm/tests/RuntimeTest.php
Accidentally introduced a break in: https://github.com/php-runtime/runtime/pull/47 that the `HttpCache` instance which example in Sulu is created in the Front Controller is not longer supported: https://github.com/chirimoya/sulu-skeleton-runtime/blob/30712fcfe63b14a20b636ff871e1ff02c9ec08d7/public/website.php#L23
=> Fix compatibility of Kernel as HttpCache instance

src/bref/src/ConsoleApplicationRunner.php
Fixes the issue identified in https://github.com/php-runtime/runtime/issues/61#issuecomment-879264420 when Symfony Console output would be written only to CloudWatch but not to Lambda output. Closes #61.
=> [Bref] Fix console runner output

src/bref/README.md
A follow-up to #61.
It adds/updates diffs of serverless configuration for Symfony application and Console application to make clear what Bref layers should be used in conjunction with Runtime.
The diffs are based on [Bref's ducumentation](https://bref.sh/docs/frameworks/symfony.html#setup) (`serverless.yml` from Symfony Flex recipe for `bref/symfony-bridge`).
=> [Bref] Clarify serverless configuration for Symfony

src/swoole/src/LaravelRunner.php, src/swoole/src/SymfonyRunner.php, src/swoole/tests/Unit/LaravelRunnerTest.php, src/swoole/tests/Unit/SymfonyRunnerTest.php
I've noticed that all responses, regardless of whether they were **201**, **404**, **500**, were returned with the same status code **200**. This PR contains the fix for both runners: Laravel and Symfony.
=> Fixed Swoole response status code

src/bref/src/Runtime.php
Switching to `$_SERVER['_HANDLER']` is working as expected. I tested it on Lambda.
=> Added error handling with the _HANDLER string

src/bref/bin/bref-local-handler.php, src/bref/composer.json, src/bref/src/LocalRunner.php, src/bref/src/Runtime.php
This is a convent way for all non-HTTP handlers to be invoked locally. It is a replacement for `./vendor/bin/bref local`. `./vendor/bin/bref local` does not work with the runtime component. 
To invoke the `App\Lambda\MyLambda` service
```
./vendor/bin/bref-local-handler.php ./bin/container.php:App\\Lambda\\MyLambda 
```
To invoke the `App\Lambda\MyLambda` service with some event data
```
./vendor/bin/bref-local-handler.php ./bin/container.php:App\\Lambda\\MyLambda '{"foo":"bar"}'
```
To invoke the `App\Lambda\MyLambda` service with some event data stored in a file
```
./vendor/bin/bref-local-handler.php ./bin/container.php:App\\Lambda\\MyLambda example/input.json
```
=> Add bref-local-handler.php to invoke bref handlers locally

src/swoole/src/ServerFactory.php, src/swoole/tests/Unit/ServerFactoryTest.php
This PR adds support of the missing 4th parameter in the Swoole's server constructor `$sock_type`. This parameter is extremely important when configuring SSL/TLS and when enabling the HTTP2 support.
=> Add Swoole's Server socket type

composer.json, src/bref/composer.json, src/roadrunner-symfony-nyholm/composer.json, src/roadrunner-symfony-nyholm/src/Runner.php, src/roadrunner-symfony-nyholm/src/Runtime.php, src/roadrunner-symfony-nyholm/tests/RuntimeTest.php, src/swoole/composer.json
This is build on top of the following refractoring: https://github.com/symfony/symfony/pull/41390
Fixes:
TODO:
=> Remove roadrunner specific session handling

src/bref/README.md
=> [Bref] Add docs about how to invoke handlers from CLI

src/bref/composer.json, src/bref/src/SymfonyRequestBridge.php, src/bref/tests/SymfonyRequestBridgeTest.php
As said in #77, currently we are loosing invocation and request context from AWS Lambda for the SymfonyHttpHandler.
Small PR to add it to the ServerBag of the Request object, to retrieve it in the code.
=> [Bref] Add invocation and request context to the Request ServerBag

composer.json, src/bref/CHANGELOG.md, src/bref/composer.json, src/bref/src/BrefRunner.php
Follow up after https://github.com/brefphp/bref/pull/1013
=> [Bref] Restart after uncaught exception

src/swoole/src/LaravelRunner.php, src/swoole/src/SymfonyRunner.php
According to Symfony [The Workflow of a Request](https://symfony.com/doc/current/components/http_kernel.html#the-workflow-of-a-request)
We need to trigger the kernel.terminate event after response was sent.
=> add symfony http kernel terminate hook

src/bref/bref/Context.php, src/bref/bref/Handler.php, src/bref/bref/autoload.php, src/bref/composer.json, src/bref/src/Runtime.php
This builds on #88
If we use Handlers, Console or Container applications. We don't really need to install bref/bref
=> [Bref] Add possibility to use without bref/bref

README.md
- Change "Since most modern PHP application is based on..." to "Since most modern PHP applications are based on..."
- Reflow the paragraph to 84 characters, which seems to be the current way.
=> Fix a tiny grammar bug in README.md

src/swoole/phpunit.xml.dist, src/swoole/src/SymfonyHttpBridge.php, src/swoole/tests/Unit/RuntimeTest.php, src/swoole/tests/Unit/SymfonyHttpBridgeTest.php
This change ensures that, when converting a `StreamedResponse` to output within `php-runtime/swoole`,
the output is streamed chunk-by-chunk, instead of being buffered in its entirety, and then being
sent out to the swooler server all in one shot.
This should fix some obvious performance, latency and memory issues related to streaming common responses
assembled by PHP-side processes.
Note: you will still need to disable symfony's `StreamedResponseListener` when working with this package.
Fixes #115
=> Fix #115 - buffer each `StreamedResponse` chunk when sending data to swoole worker output

src/reactphp/README.md, src/reactphp/composer.json, src/reactphp/src/Runner.php, src/reactphp/src/Runtime.php, src/reactphp/src/ServerFactory.php, src/reactphp/tests/RunnerTest.php, src/reactphp/tests/RuntimeTest.php, src/reactphp/tests/ServerFactoryTest.php
Improving react code, based loosely on the swoole runtime:
- allow setting react host via options, env/server vars
- refactor react http server creation into a factory
- more react tests
- bump minimum required react version to allow replacement of some deprecated classes
- handle and exit on container kill/stop signals (sigterm + sigkill)
The main objective is to allow listening on interfaces other than 127.0.0.1 (eg 0.0.0.0 for container-based installations)
=> [react] runtime improvements

README.md, phpstan-baseline.neon, psalm.baseline.xml, src/frankenphp-symfony/.github/FUNDING.yml, src/frankenphp-symfony/.gitignore, src/frankenphp-symfony/CHANGELOG.md, src/frankenphp-symfony/LICENSE, src/frankenphp-symfony/README.md, src/frankenphp-symfony/composer.json, src/frankenphp-symfony/phpunit.xml.dist, src/frankenphp-symfony/src/Runner.php, src/frankenphp-symfony/src/Runtime.php, src/frankenphp-symfony/tests/RunnerTest.php, src/frankenphp-symfony/tests/RuntimeTest.php, src/frankenphp-symfony/tests/function-mock.php
Add a runtime for the worker mode of [FrankenPHP](https://frankenphp.dev). To be released this afternoon at ForumPHP!
=> feat: add a runtime for FrankenPHP with Symfony

src/frankenphp-symfony/composer.json
Allows playing with https://github.com/dunglas/frankenphp-demo with PHP 8.1 installed locally and without need to tweak the README instructions. Otherwise:
Let's revisit this only once php 8.2 stable gets released.
=> [FrankenPHP] Relax php requirement - allow 8.0

.github/workflows/static.yml, composer.json, psalm.baseline.xml, src/google-cloud/composer.json
Currently composer normalize is erroring and psalm is erroring which blocks other pull requests. This will udpate the composer.json and add the parent::__construct($options); call to the baseline.
=> Update psalm and composer normalize

src/roadrunner-symfony-nyholm/composer.json
Reverts php-runtime/runtime#138
This was accidently merged by auto merge. But the CI is failing and we should have a deeper look at why it is happening.
=> Revert "feat(road-runner): allow ^2023.1.0 and ^2.0"

src/reactphp/src/ServerFactory.php
Fix for:
> Fatal error: Error installing signal handler for 9 in /app/vendor/react/event-loop/src/StreamSelectLoop.php on line 161
From https://www.php.net/manual/en/function.pcntl-signal.php#83981 (14 years old):
>  You cannot assign a signal handler for SIGKILL (kill -9).
=> Change SIGKILL to SIGHUP

src/frankenphp-symfony/src/Runner.php
Triggering the garbage collector after the request has been handled and when the worker may be idle prevents the garbage collection from being randomly done in the middle of the handling of a request (which delays the delivery of the HTTP response).
Another option, that is done by Laravel Octone, is to trigger the GC when a configurable amount of memory has been consumed instead of after every request.
I think this patch is good enough for FrankenPHP as usually many workers will be available.
=> frankenphp-symfony: call gc_collect_cycles() after handling request

src/frankenphp-symfony/src/Runner.php
Follows https://github.com/symfony/symfony/pull/52079.
cc @nicolas-grekas
=> feat: set APP_RUNTIME_MODE for frankenphp-symfony

psalm.baseline.xml, src/frankenphp-symfony/src/Runner.php
Backport of some micro-optimizations by @francislavoie https://github.com/laravel/octane/pull/764#discussion_r1375165179
=> frankenphp-symfony: perf improvement

composer.json, src/roadrunner-symfony-nyholm/CHANGELOG.md, src/roadrunner-symfony-nyholm/composer.json
@thecaliskan can you verify if this works for you?
=> Psr http message

src/swoole-nyholm/README.md, src/swoole/README.md
https://swoole.co.uk/ redirects to OpenSwoole, which is a different extension than Swoole. This updates the README.md file with the correct examples for Swoole.
=> Updating links and examples to use Swoole instead of OpenSwoole

src/frankenphp-symfony/src/Runner.php
Fixes the issue that the loop doesn't exist when `$loopMax` is reached, but `$loopMax+1`. Please refer to https://github.com/php-runtime/runtime/pull/173 for details.
=> frankenphp: break loop when loopMax is reached

src/frankenphp-symfony/src/Runner.php
Use the new [`xdebug_connect_to_client()`](https://xdebug.org/docs/all_functions#xdebug_connect_to_client) function if available to allow debugging with Xdebug in worker mode.
=> [FrankenPHP] Add Xdebug support
